Repository CEA-COSMIC/ModOpt, pull requests merged in 2021-04, with the labels that each got.

#112 Add support for tensorflow backend which allows for differentiability
  modopt/base/backend.py
  modopt/math/matrix.py
  modopt/opt/algorithms.py
  setup.cfg
Labels: enhancement

#116 Fix 115
  modopt/opt/algorithms.py
  modopt/tests/test_opt.py
Labels: bug

#124 MInor bug in `get_array_module`
  modopt/base/backend.py
Labels: bug

#128 Release cleanup
  MANIFEST.in
  README.md
  docs/source/dependencies.rst
  docs/source/index.rst
  setup.py
Labels: clean up

#114 Version 1.5.1 patch release
  .github/workflows/ci-build.yml
  MANIFEST.in
  README.md
  docs/source/dependencies.rst
  docs/source/index.rst
  modopt/base/backend.py
  modopt/math/matrix.py
  modopt/opt/algorithms.py
  modopt/tests/test_base.py
  modopt/tests/test_opt.py
  setup.cfg
  setup.py
Labels: release
