Repository CEA-COSMIC/ModOpt, pull requests merged in 2021-12, with the labels that each got.

#196 Add Gradient descent algorithms
  docs/source/refs.bib
  modopt/opt/algorithms/__init__.py
  modopt/opt/algorithms/base.py
  modopt/opt/algorithms/forward_backward.py
  modopt/opt/algorithms/gradient_descent.py
  modopt/opt/algorithms/primal_dual.py
  modopt/tests/test_algorithms.py
  setup.cfg
Labels: enhancement

#198 Release cleanup
  MANIFEST.in
  README.md
  develop.txt
  docs/requirements.txt
  docs/source/about.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/cosmostat_logo.jpg
  docs/source/dependencies.rst
  docs/source/index.rst
  docs/source/neurospin_logo.png
  docs/source/refs.bib
  docs/source/z_ref.rst
  modopt/base/backend.py
  modopt/base/np_adjust.py
  modopt/base/observable.py
  modopt/base/transform.py
  modopt/base/types.py
  modopt/base/wrappers.py
  modopt/math/convolve.py
  modopt/math/matrix.py
  modopt/math/stats.py
  modopt/opt/algorithms/__init__.py
  modopt/opt/algorithms/base.py
  modopt/opt/algorithms/forward_backward.py
  modopt/opt/algorithms/gradient_descent.py
  modopt/opt/algorithms/primal_dual.py
  modopt/opt/cost.py
  modopt/opt/gradient.py
  modopt/opt/linear.py
  modopt/opt/proximity.py
  modopt/opt/reweight.py
  modopt/signal/noise.py
  modopt/signal/positivity.py
  modopt/signal/svd.py
  modopt/signal/validation.py
  modopt/signal/wavelet.py
  setup.cfg
  setup.py
Labels: clean up

#200 Version 1.6.0 release
  .pyup.yml
  MANIFEST.in
  README.md
  develop.txt
  docs/requirements.txt
  docs/source/about.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/cosmostat_logo.jpg
  docs/source/dependencies.rst
  docs/source/index.rst
  docs/source/neurospin_logo.png
  docs/source/refs.bib
  docs/source/z_ref.rst
  modopt/base/backend.py
  modopt/base/np_adjust.py
  modopt/base/observable.py
  modopt/base/transform.py
  modopt/base/types.py
  modopt/base/wrappers.py
  modopt/math/convolve.py
  modopt/math/matrix.py
  modopt/math/stats.py
  modopt/opt/algorithms/__init__.py
  modopt/opt/algorithms/base.py
  modopt/opt/algorithms/forward_backward.py
  modopt/opt/algorithms/gradient_descent.py
  modopt/opt/algorithms/primal_dual.py
  modopt/opt/cost.py
  modopt/opt/gradient.py
  modopt/opt/linear.py
  modopt/opt/proximity.py
  modopt/opt/reweight.py
  modopt/signal/noise.py
  modopt/signal/positivity.py
  modopt/signal/svd.py
  modopt/signal/validation.py
  modopt/signal/wavelet.py
  modopt/tests/test_algorithms.py
  requirements.txt
  setup.cfg
  setup.py
Labels: release
